### ISSUE TITLE
how did you

### ISSUE THREAD

**Issue by rullinoiz** [tornadus11/tornadus11.github.io#1]
make the gif

cras

**Comment by Slappy826** [comment]
ur mom is in it

**Comment by CMD-X** [comment]
realy?!?1

**Comment by VMpc** [comment]
okay so first, you get a pizza. Then you go to Slappys house and say hi with that pizza, You're done!
![LMFAO](https://user-images.githubusercontent.com/50967051/114291707-7a52a180-9a57-11eb-8d96-b6d95a9ce121.png)

**Comment by VMpc** [comment]
oh and don't forget the fursuit right @Slappy826

**Comment by rullinoiz** [comment]
> ur mom is in it

i didnt know we were siblings

**Comment by VMpc** [comment]
> 
> 
> > ur mom is in it
> 
> i didnt know we were siblings

I made you two siblings

**Comment by CMD-X** [comment]
Wat The!!``````````````````````````_true_**poop**

Hahaha!!!11

**Comment by VMpc** [comment]
> 
> 
> Wat The!!``````````````````````````_true_**poop**
> 
> Hahaha!!!11

stop talking about your own script

**Comment by CMD-X** [comment]
> > Wat The!!``````````````````````````_true_**poop**
> > Hahaha!!!11
> 
> stop talking about your own script

- Yes
- No
- =
- No

**Comment by VMpc** [comment]
> 
> 
> > > Wat The!!``````````````````````````_true_**poop**
> > > Hahaha!!!11
> > 
> > 
> > stop talking about your own script
> 
>     * Yes
> 
>     * No
> 
>     * =
> 
>     * No

tell slappy I said hi in seed I know he loves me right @Slappy826 
![e3d08a0c18dbb4477126be12a3de411b](https://user-images.githubusercontent.com/50967051/114291815-5b084400-9a58-11eb-894f-777cd186492c.png)

**Comment by CMD-X** [comment]
> > > > Wat The!!``````````````````````````_true_**poop**
> > > > Hahaha!!!11
> > > 
> > > 
> > > stop talking about your own script
> > 
> > 
> > ```
> > * Yes
> > 
> > * No
> > 
> > * =
> > 
> > * No
> > ```
> 
> tell slappy I said hi in seed I know he loves me right @Slappy826
> ![e3d08a0c18dbb4477126be12a3de411b](https://user-images.githubusercontent.com/50967051/114291815-5b084400-9a58-11eb-894f-777cd186492c.png)

he said ur cringe ( 672 F P G h % )

**Comment by CMD-X** [comment]
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

**Comment by VMpc** [comment]
That's no fun, don't worry slappy we can still be together I don't judge @Slappy826 
![SantaFox](https://user-images.githubusercontent.com/50967051/114291872-cb16ca00-9a58-11eb-9d92-f1a7e430a446.png)

**Comment by CMD-X** [comment]
- [ How] Win
`W ()`

> True

### YUP YUP YUP
**this is issue**

**Comment by VMpc** [comment]
Hello, How did you make this sophisticated mp4 crash my discord??? I need to know how to use ffmpeg. Please and thank you.

**Comment by CMD-X** [comment]
@tornadus Please Clsoe ThIS uissue ShitPoster Alert

**Comment by VMpc** [comment]
> 
> 
> @tornadus Please Clsoe ThIS uissue ShitPoster Alert

yeah @tornadus please close this issue, I would like to talk to slappy in my private quarters.

**Comment by CMD-X** [comment]
@rullinoiz Please Join The Discord So We Can Support you Further...

**Comment by VMpc** [comment]
https://discord.gg/h4A92egS Here is the server.
